version: '3'

services:
  marketplace-postgres-compose:
    image: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: marketplace
    ports:
      - "5432:5432"
    networks:
      - postgres-compose-network
      
  marketplace-pgadmin-compose:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com.br"
      PGADMIN_DEFAULT_PASSWORD: "password"
    ports:
      - "5431:80"
    depends_on:
      - marketplace-postgres-compose
    networks:
      - postgres-compose-network

networks: 
  postgres-compose-network:
    driver: bridge
